version: '3'

services:

    caddy:
        image: klutchell/caddy
        container_name: caddy
        ports:
            - '80:80'
            - '443:443'
            - '2015:2015'
        restart: unless-stopped
        volumes:
            - 'caddy_root:/www'
            - 'caddy_certs:/root/.caddy'
        environment:
            - 'TZ=America/Toronto'
            - 'CADDY_EMAIL=example@address.com'

volumes:

    caddy_root:
    caddy_certs: